#pragma once

#include "backtest/alpha_decay.hpp"
#include "backtest/backtest_engine.hpp"
#include "book/l2_book.hpp"
#include "common/types.hpp"

#include <algorithm>
#include <cstdio>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <string>
#include <vector>

namespace oms::ui {

struct SessionReport {
    L2Snapshot final_book{};
    BacktestResult backtest{};
    std::vector<AlphaDecayPoint> decay_curve;
    std::vector<double> composite_history;
    std::vector<double> mid_history;
    std::vector<double> spread_history;
    std::vector<double> equity_history;
    uint64_t book_adds{0};
    uint64_t book_cancels{0};
    uint64_t book_executes{0};
    std::size_t order_count{0};
    int wal_commands{0};
    int wal_trades{0};
    int spsc_produced{0};
    int spsc_trades{0};
    std::string data_source;
    std::string ticker;
    std::size_t replay_events{0};
    double avg_spread{0.0};
    uint64_t real_trade_count{0};
    uint64_t real_volume{0};
};

namespace detail {

inline std::string fmt_pct(double frac, int decimals = 2) {
    std::ostringstream os;
    os << std::fixed << std::setprecision(decimals) << (frac * 100.0) << "%";
    return os.str();
}

inline std::string fmt_num(double v, int decimals = 4) {
    std::ostringstream os;
    os << std::fixed << std::setprecision(decimals) << v;
    return os.str();
}

inline std::string svg_polyline(const std::vector<double>& series, const char* stroke,
                                double width = 400, double height = 120) {
    if (series.size() < 2) return "";
    double lo = *std::min_element(series.begin(), series.end());
    double hi = *std::max_element(series.begin(), series.end());
    if (hi - lo < 1e-12) hi = lo + 1.0;

    std::ostringstream os;
    os << "<svg viewBox=\"0 0 " << width << " " << height << "\" preserveAspectRatio=\"none\">\n";
    os << "<polyline fill=\"none\" stroke=\"" << stroke << "\" stroke-width=\"2\" points=\"";
    const std::size_t n = series.size();
    for (std::size_t i = 0; i < n; ++i) {
        double x = width * static_cast<double>(i) / static_cast<double>(n - 1);
        double y = (height - 10) - (height - 20) * (series[i] - lo) / (hi - lo);
        os << x << "," << y << " ";
    }
    os << "\"/></svg>";
    return os.str();
}

}  // namespace detail

inline bool write_html_report(const std::string& path, const SessionReport& r) {
    std::ofstream out(path, std::ios::trunc);
    if (!out) return false;

  const bool is_replay = r.replay_events > 0;
  const auto& equity = !r.equity_history.empty() ? r.equity_history : r.backtest.equity_curve;

    out << R"(<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>OMS Session Report</title>
<style>
  :root { --bg:#0f1419; --card:#1a2332; --text:#e7ecf3; --bid:#3dd68c; --ask:#f07178; --accent:#6cb6ff; --muted:#94a3b8; }
  * { box-sizing: border-box; }
  body { font-family: 'Segoe UI', system-ui, sans-serif; background: var(--bg); color: var(--text); margin: 0; padding: 2rem; line-height: 1.5; }
  h1 { color: var(--accent); margin-top: 0; }
  h2 { border-bottom: 1px solid #334155; padding-bottom: 0.3rem; font-size: 1.1rem; margin-top: 1.75rem; }
  h3 { font-size: 0.95rem; color: var(--muted); margin: 0 0 0.75rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.04em; }
  .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; }
  .card { background: var(--card); border-radius: 8px; padding: 1rem 1.25rem; }
  .metric { font-size: 1.6rem; font-weight: 600; color: var(--accent); }
  .metric.pos { color: var(--bid); }
  .metric.neg { color: var(--ask); }
  .label { font-size: 0.85rem; opacity: 0.75; }
  .sub { font-size: 0.8rem; color: var(--muted); margin-top: 0.25rem; }
  table { width: 100%; border-collapse: collapse; font-size: 0.9rem; }
  th, td { padding: 0.35rem 0.5rem; text-align: right; }
  th { text-align: left; opacity: 0.8; }
  .bid { color: var(--bid); }
  .ask { color: var(--ask); }
  .bar-row { display: flex; align-items: center; gap: 0.5rem; margin: 0.25rem 0; }
  .bar { height: 14px; border-radius: 3px; min-width: 2px; }
  .bar-bid { background: var(--bid); }
  .bar-ask { background: var(--ask); }
  svg { width: 100%; height: 140px; display: block; }
  .ladder-mid { text-align: center; color: #fbbf24; padding: 0.4rem 0; border-top: 1px dashed #334155; border-bottom: 1px dashed #334155; margin: 0.5rem 0; font-size: 0.9rem; }
  .chart-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 1rem; }
  footer { margin-top: 2rem; opacity: 0.5; font-size: 0.8rem; }
</style>
</head>
<body>
<h1>OMS Session Report</h1>
<p>Generated by <strong>oms</strong> — ultra-low-latency order management system.</p>
)";

    if (!r.ticker.empty() || !r.data_source.empty()) {
        out << "<p><strong>Data:</strong> " << r.ticker << " &mdash; " << r.data_source;
        if (is_replay) out << " &middot; " << r.replay_events << " events replayed";
        out << "</p>\n";
    }

    if (is_replay) {
        out << "<h2>Market Microstructure</h2><h3>Exchange replay statistics</h3>\n<div class=\"grid\">\n";
        out << "<div class=\"card\"><div class=\"label\">Submissions</div><div class=\"metric\">" << r.book_adds
            << "</div></div>\n";
        out << "<div class=\"card\"><div class=\"label\">Cancels</div><div class=\"metric\">" << r.book_cancels
            << "</div></div>\n";
        out << "<div class=\"card\"><div class=\"label\">Executions</div><div class=\"metric\">"
            << r.real_trade_count << "</div></div>\n";
        out << "<div class=\"card\"><div class=\"label\">Volume (shares)</div><div class=\"metric\">"
            << r.real_volume << "</div></div>\n";
        if (r.avg_spread > 0) {
            out << "<div class=\"card\"><div class=\"label\">Avg spread</div><div class=\"metric\">$"
                << detail::fmt_num(r.avg_spread / 10000.0, 4) << "</div></div>\n";
        }
        if (r.final_book.best_bid != INVALID_PRICE) {
            out << "<div class=\"card\"><div class=\"label\">Best bid / ask</div><div class=\"metric\" style=\"font-size:1.1rem\">$"
                << detail::fmt_num(r.final_book.best_bid / 10000.0, 3) << " / $"
                << detail::fmt_num(r.final_book.best_ask / 10000.0, 3) << "</div></div>\n";
        }
        out << "</div>\n";
    }

    out << "<h2>Signal Backtest</h2><h3>Composite alpha strategy (simulated)</h3>\n<div class=\"grid\">\n";
    std::string ret_class = r.backtest.total_return >= 0 ? "pos" : "neg";
    out << "<div class=\"card\"><div class=\"label\">Total return</div><div class=\"metric " << ret_class
        << "\">" << detail::fmt_pct(r.backtest.total_return) << "</div>"
        << "<div class=\"sub\">Final equity: " << detail::fmt_num(r.backtest.final_equity, 4) << "</div></div>\n";
    out << "<div class=\"card\"><div class=\"label\">Sharpe (est.)</div><div class=\"metric\">"
        << detail::fmt_num(r.backtest.sharpe, 2) << "</div></div>\n";
    out << "<div class=\"card\"><div class=\"label\">Max drawdown</div><div class=\"metric\">"
        << detail::fmt_pct(r.backtest.max_drawdown) << "</div></div>\n";
    out << "<div class=\"card\"><div class=\"label\">Strategy trades</div><div class=\"metric\">"
        << r.backtest.trade_count << "</div>"
        << "<div class=\"sub\">Turnover: " << detail::fmt_num(r.backtest.turnover, 1) << "</div></div>\n";
    out << "</div>\n";

    out << "<h2>Charts</h2><div class=\"chart-grid\">\n";

    if (equity.size() >= 2) {
        out << "<div class=\"card\"><div class=\"label\">Equity curve</div>\n";
        out << detail::svg_polyline(equity, "#3dd68c") << "</div>\n";
    }
    if (r.mid_history.size() >= 2) {
        out << "<div class=\"card\"><div class=\"label\">Mid price</div>\n";
        out << detail::svg_polyline(r.mid_history, "#6cb6ff") << "</div>\n";
    }
    if (r.spread_history.size() >= 2) {
        out << "<div class=\"card\"><div class=\"label\">Bid-ask spread ($)</div>\n";
        out << detail::svg_polyline(r.spread_history, "#f07178") << "</div>\n";
    }
    if (r.composite_history.size() >= 2) {
        out << "<div class=\"card\"><div class=\"label\">Composite signal</div>\n";
        out << detail::svg_polyline(r.composite_history, "#a78bfa") << "</div>\n";
    }
    out << "</div>\n";

    out << "<h2>Order Book Ladder</h2><div class=\"card\"><table>\n";
    out << "<tr><th>Side</th><th>Price</th><th>Qty</th><th>Depth</th></tr>\n";
    const int depth = 8;
    Quantity max_q = 1;
    for (int i = 0; i < r.final_book.ask_count && i < depth; ++i)
        max_q = std::max(max_q, r.final_book.asks[i].qty);
    for (int i = 0; i < r.final_book.bid_count && i < depth; ++i)
        max_q = std::max(max_q, r.final_book.bids[i].qty);

    for (int i = std::min(depth, r.final_book.ask_count) - 1; i >= 0; --i) {
        const auto& lv = r.final_book.asks[i];
        int pct = static_cast<int>(100.0 * lv.qty / max_q);
        out << "<tr class=\"ask\"><td>ASK</td><td>$" << detail::fmt_num(lv.price / 10000.0, 3)
            << "</td><td>" << lv.qty << "</td><td><div class=\"bar-row\"><div class=\"bar bar-ask\" style=\"width:"
            << pct << "%\"></div></div></td></tr>\n";
    }

    if (r.final_book.best_bid != INVALID_PRICE && r.final_book.best_ask != INVALID_PRICE) {
        Price sp = r.final_book.spread();
        out << "<tr><td colspan=\"4\" class=\"ladder-mid\">Mid $"
            << detail::fmt_num(r.final_book.mid_price() / 10000.0, 4) << " &middot; Spread $"
            << detail::fmt_num(sp / 10000.0, 4);
        if (sp <= 0)
            out << " &middot; <span style=\"color:#f07178\">⚠ crossed book — check replay integrity</span>";
        out << "</td></tr>\n";
    }

    for (int i = 0; i < std::min(depth, r.final_book.bid_count); ++i) {
        const auto& lv = r.final_book.bids[i];
        int pct = static_cast<int>(100.0 * lv.qty / max_q);
        out << "<tr class=\"bid\"><td>BID</td><td>$" << detail::fmt_num(lv.price / 10000.0, 3)
            << "</td><td>" << lv.qty << "</td><td><div class=\"bar-row\"><div class=\"bar bar-bid\" style=\"width:"
            << pct << "%\"></div></div></td></tr>\n";
    }
    out << "</table></div>\n";

    if (!r.decay_curve.empty()) {
        out << "<h2>Alpha Decay (IC vs horizon)</h2><div class=\"card\"><table>\n";
        out << "<tr><th>Horizon (ms)</th><th>IC</th><th>Samples</th></tr>\n";
        for (const auto& pt : r.decay_curve) {
            double ms = static_cast<double>(pt.horizon_ns) / 1e6;
            out << "<tr><td>" << detail::fmt_num(ms, 1) << "</td><td>" << detail::fmt_num(pt.ic, 4)
                << "</td><td>" << pt.sample_count << "</td></tr>\n";
        }
        out << "</table></div>\n";
    }

    if (!is_replay) {
        out << "<h2>Engine Stats</h2><div class=\"grid\">\n";
        out << "<div class=\"card\"><div class=\"label\">Book adds / cancels / executes</div><div class=\"metric\">"
            << r.book_adds << " / " << r.book_cancels << " / " << r.book_executes << "</div></div>\n";
        if (r.spsc_produced > 0) {
            out << "<div class=\"card\"><div class=\"label\">SPSC commands / trades</div><div class=\"metric\">"
                << r.spsc_produced << " / " << r.spsc_trades << "</div></div>\n";
        }
        out << "</div>\n";
    }

    out << R"(<footer>OMS — MIT License · Fixed-point prices (×10⁴) · For research &amp; education only.</footer>
</body>
</html>
)";
    return true;
}

}  // namespace oms::ui
